source 'https://rubygems.org/'

ruby '2.4.0'

gem 'actionpack', '~> 5.1.2'
gem 'activesupport', '~> 5.1.2'
gem 'activemerchant'
gem 'railties', '~> 5.1.4'
gem 'sprockets', '3.7.1'

gem 'rails', '~> 5.1.3'
gem 'pg', '~> 0.18'
gem 'sass-rails', '~> 5.0.6'
gem 'uglifier', '>= 1.3.0'
gem 'nokogiri'
gem 'jquery-rails'
gem 'faker'
gem 'foundation-rails'
gem 'devise'
gem 'carrierwave', '~> 1.0'
gem 'foreman'
gem 'mini_magick', '3.8.0'
gem 'fog-aws'
gem 'httparty'
gem 'rack-cors', :require => 'rack/cors'

# add webpack support for react
gem 'webpacker', '~> 3.0'
# add webpacker-react to access rails through props
# gem 'webpacker-react', "~> 0.3.2"

group :development do
  gem 'listen', '~> 3.1.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :development, :test do
  gem 'capybara'
  gem 'factory_girl'
  gem 'factory_girl_rails'
  gem 'rspec-rails', '~> 3.6.1'
  gem 'pry-rails'
  gem 'shoulda', require: false
  gem 'shoulda-matchers', require: false
  gem 'valid_attribute'
  gem 'dotenv-rails'
end

group :test do
  gem 'launchy', require: false
  gem "database_cleaner"
end

group :production do
  gem 'rails_12factor'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
